### ISSUE TITLE
1組のdocker-compose.ymlとDockerfileで複数のコンテナを実行できるようにしたい

### ISSUE THREAD

**Issue by v97ug** [v97ug/question#14]
今railsの勉強をしていてるが、railsをローカルの環境にインストールするのは面倒なのでDockerで管理したい。1組のdocker-compose.yml・database.yml・Dockerfileで複数のコンテナをテスト用に起動できるようにしたい。

ただ、僕はdocker-compose魔法見習いのため、docker-composeのコマンドが`docker-compose build`と`docker-compose up -d`しかわからない。。。

現状、docker-compose.ymlのコンテナ名とポート番号を一回一回変えることで複数のコンテナを起動することに成功した。しかしできれば、dockerもしくはdocker-composeのコマンドを使用する時にポート番号やコンテナ名が指定できるようにしたい。

そのような方法はあるだろうか？

以下ファイル

## docker-compose.yml

```yaml:docker-compose.yml
version: '3'
services:
  rails:
    build: .
    image: my/rails
    container_name: 'rails3'
    tty: true
    ports:
      - "11183:3000"
    environment:
      APP_DATABASE: 'example'
      APP_DATABASE_USER: 'app'
      APP_DATABASE_PASSWORD: 'development'
    volumes:
      - app-data:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: 'mysql3'
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'example'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'development'
    ports:
      - '3303:3303'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  app-data:
     driver: local
  mysql-data:
    driver: local
```

## database.yml

```yaml:database.yml
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['APP_DATABASE'] %>
  username: <%= ENV['APP_DATABASE_USER'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  host: mysql

test:
  <<: *default
  host: mysql

production:
  <<: *default
  host: mysql
```

## Dockerfile

```Dockerfile
FROM ruby:2.5

ENV LANG C.UTF-8
ENV WORKSPACE=/usr/local/src

# install bundler.
RUN apt-get update && \
    apt-get install -y vim less && \
    apt-get install -y build-essential libpq-dev && \
    gem install bundler && \
    apt-get clean && \
    rm -r /var/lib/apt/lists/*

# create user and group.
RUN groupadd -r --gid 1000 rails && \
    useradd -m -r --uid 1000 --gid 1000 rails

# create directory.
RUN mkdir -p $WORKSPACE $BUNDLE_APP_CONFIG && \
    chown -R rails:rails $WORKSPACE && \
    chown -R rails:rails $BUNDLE_APP_CONFIG

USER rails
WORKDIR $WORKSPACE

# bundle install.
COPY --chown=rails:rails Gemfile $WORKSPACE/Gemfile
RUN bundle install && \
    bundle exec rails new . --force --database=mysql && \
    { \
        echo "gem 'therubyracer', platforms: :ruby"; \
    } >> $WORKSPACE/Gemfile && \
    bundle update
COPY --chown=rails:rails database.yml $WORKSPACE/config/database.yml

EXPOSE  3000
CMD ["rails", "server", "-b", "0.0.0.0"]
```
